package org.example.exception;

public enum ErrorCode {
    VALIDATION_EXCEPTION,
    FIELD_EXCEPTION,
    ENTITY_NON_EXIST,
    USERNAME_NOT_FOUND,
    DIRECTORY_NOT_CREATE,
    FILENAME_WITH_INVALID_PATH_SEQUENCE,
    FILE_IS_NOT_STORE,
    BALANCE_LESS_0,
    BALANCE_NOT_UPDATED,
    ;
}
